using System;
using Yaclops.Commands;


namespace Yaclops
{
    /// <summary>
    /// Settings that alter the default behavior of the parser.
    /// </summary>
    /// <typeparam name="T">The type (usually an interface) of the commands generated by the parser.</typeparam>
    public class CommandLineParserSettings<T> : GlobalParserSettings
    {
        /// <summary>
        /// Constructor
        /// </summary>
        public CommandLineParserSettings()
        {
            NullCommand = () => default(T);
        }

        /// <summary>
        /// A func that returns the command that is returned when help or another internal command is parsed.
        /// </summary>
        public Func<T> NullCommand { get; set; }
    }



    internal class DefaultSubCommandSettings : CommandLineParserSettings<ISubCommand>
    {
        public DefaultSubCommandSettings()
        {
            NullCommand = () => new NullSubCommand();
        }
    }
}
